### PR TITLE
Remove jQuery dependency

### PR DESCRIPTION
**Pull request by chazeah**
Fixes https://github.com/djrrb/Bungee/issues/56.

* Didn't change any functionality or restructure the code
* Same browser support as before
* Added some additional examples
* Removed unnecessary white space and addressed some lint issues

Love the font, and wanted to contribute somehow!

### CODE REVIEW

**Comment by RoelN** [comment]
Haven't tested it, but code looks good to me! 👍

**Comment by chazeah** [comment]
Not sure if ya'll have a more formal process, but you're free to merge it whenever you're ready!

**Comment by chrissam42** [comment]
Thanks very much! I had considered doing it without jQuery originally but ultimately went the lazy route.

I might be wrong about this, but I think this actually ups the minimum IE version from 9 to 10, at least according to MDN's listing of IE 10 as the first version that supports Element.classList. But I can live with that.

I fixed a few minor bugs in @chazeah's updates, and found a few more major ones that had been covered up by the use of jQuery (like duplicate layers being added and then all updated at once by the jQuery calls).

This is great, thanks again @chazeah.

**Comment by chrissam42** [comment]
This pull request was replaced with #64 with my extra commit.

**Comment by chazeah** [comment]
No prob! Glad to help.

**Pull request merged**
