### PR TITLE
Article draft added

### PR DESCRIPTION
**Pull request by vv-monsalve**
@djrrb, @justvanrossum 

At GF, we are enhancing the About section of the fonts to include images and more descriptive text about the fonts, their features and their advantages.

This PR introduces a preliminary version of the required 'ARTICLE.en_us.html' file for Bungee Tint, which we are about to onboard. However, this draft is intended to serve as a template for all other related font families, and the dedicated paragraph for each font will need to be customized to describe each case specifically.

You can find more information about the [article file here](https://googlefonts.github.io/gf-guide/article.html) and the [necessary images here](https://googlefonts.github.io/gf-guide/promotion). Please review them and merge this draft, which can be used as a starting point for editing or complementing.

I've included a brief paragraph at the end acknowledging Marte and Just's work; please adjust it.

### CODE REVIEW

**Comment by djrrb** [comment]
I’ve merged and will make a few edits. @justvanrossum feel free to edit as well.

**Comment by vv-monsalve** [comment]
Hi @djrrb are you planning to include some images for the article? We are getting closer to the onboarding time, and it seems this piece is mostly the main one we'll need now :)

**Comment by djrrb** [comment]
I just added some images to `documentation/article/images`...is that correct? Am I also supposed to include them in the `ARTICLE.en_us.html`?

**Comment by djrrb** [comment]
> No, I'll add them and create a PR with the changes; there, you'll be able to decide on the order or any new additions.

Thanks! FWIW my preferred order is reflected in the filenames but feel free to tweak as needed.

> The idea would be to update the About section of the non-colored fonts, too. Would you like to add a couple of images for them?

Okay I’ve added a couple images that show the basic fonts with less color and fancy layering. Let me know if you’d like to see anything else!

**Pull request merged**
